syntax = "proto3";

package iguana.v1;

import "google/protobuf/timestamp.proto";

//
service IguanaService {
    rpc CognitoEvent(CognitoEventRequest) returns (CognitoEventResponse) {}
    rpc Ping(PingRequest) returns (PingResponse) {}
    rpc RandomNote(RandomNoteRequest) returns (RandomNoteResponse) {}
    rpc SelectUser(SelectUserRequest) returns (SelectUserResponse) {}
    rpc UserRole(UserRoleRequest) returns (UserRoleResponse) {}
    rpc UserSuspend(UserSuspendRequest) returns (UserSuspendResponse) {}
    rpc UserUpdate(UserUpdateRequest) returns (UserUpdateResponse) {}
    rpc UserGroup(UserGroupRequest) returns (UserGroupResponse) {}
    rpc VisitorEvent(VisitorEventRequest) returns (VisitorEventResponse) {}
}

// 
message CognitoEventRequest {
    string key = 1;
    string email = 2;
    string name = 3;
}

//
message CognitoEventResponse {
    string key = 1;
    uint32 retcode = 2;
    google.protobuf.Timestamp created_at = 3;
    google.protobuf.Timestamp last_seen_at = 4;
    bool suspend_flag = 5;
    string email = 6;
    string name = 7;
    string role = 8;
}

//
message NoteMeta {
    string group_name = 1;
    string group_uuid = 2;
//    string owner_name = 3;
//    string owner_uuid = 4;
//  
//    bool admin_flag = 5;
//    bool inhibit_flag = 6;
    bool private_flag = 3;
    bool suspend_flag = 4;
//
//    int64 created_at = 9;
//    int64 modified_at = 10;
//    int64 modified_count = 22;
//
//    int32 like_count = 31;
//    int32 visit_count = 32;
    int32 mask = 5;
    int32 version = 6;

//
    string note_uuid = 7;
//    string note_message = 34;
}

//
message RandomNoteRequest {
    uint32 content_mask = 1;
}

//
message RandomNoteResponse {
    string key = 1;
    uint32 retcode = 2;
    google.protobuf.Timestamp created_at = 3;
    google.protobuf.Timestamp last_viewed_at = 4;
    string created_by_uuid = 5;
    uint32 view_count = 6;
    uint32 favorite_count = 7;
    uint32 version = 8;
    string message = 9;
}

//
message PingRequest {
    string source = 1;
}

//
message PingResponse {
    uint32 retcode = 1;
}

// 
message SelectUserRequest {
    string key = 1;
}

//
message SelectUserResponse {
    string key = 1;
    uint32 retcode = 2;
    google.protobuf.Timestamp created_at = 3;
    google.protobuf.Timestamp last_seen_at = 4;
    bool suspend_flag = 5;
    string email = 6;
    string group = 7;
    string name = 8;
    string role = 9;
}

// 
message UserGroupHeader {
    string group_uuid = 1;
    google.protobuf.Timestamp created_at = 2;
    google.protobuf.Timestamp modified_at = 3;
    bool private_flag = 4;
    string name = 5;
}

//
message UserGroupRequest {
    string user_uuid = 1;
}

//
message UserGroupResponse {
    string user_uuid = 1;
    uint32 retcode = 2;
    repeated UserGroupHeader group_header = 3;
}

//
message UserRoleRequest {
    string user_uuid = 1;
    string role = 2;
}

//
message UserRoleResponse {
    string user_uuid = 1;
    uint32 retcode = 2;
}

//
message UserSuspendRequest {
    string user_uuid = 1;
    string suspend_flag = 2;
}

//
message UserSuspendResponse {
    string user_uuid = 1;
    uint32 retcode = 2;
}

//
message UserUpdateRequest {
    string user_uuid = 1;
    google.protobuf.Timestamp last_seen = 2;
    string email = 3;
}

//
message UserUpdateResponse {
    string user_uuid = 1;
    uint32 retcode = 2;
}

//
message VisitorEventRequest {
    string address = 1;
    string target = 2;
    google.protobuf.Timestamp time_stamp = 3;
}

//
message VisitorEventResponse {
    uint32 retcode = 1;
}
