name: proto-action

on: [push]
#  push:
#    branches:
#    - main

jobs:
  proto_checks:
    name: proto lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
    
      - uses: arduino/setup-protoc@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Fetching base branch
#        run: |
#          git fetch -u origin ${{ github.base_ref }}:${{ github.base_ref }}

#      - name: Running linter, checking breaking changes
#        run: |
#          buf lint
#          buf breaking --against ".git#branch=${{ github.base_ref }}"          

#      - name: Installing protoc-gen-go
#        run: |
#          go get github.com/golang/protobuf/protoc-gen-go
#          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc          