name: proto-action

on: [push]
#  push:
#    branches:
#    - main

jobs:
  proto_checks:
    name: proto lint
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: bufbuild/buf-setup-action@v1.30.1
        with:
          github_token: ${{ github.token }}

      - run: buf --version

      - name: buf-lint
        uses: bufbuild/buf-lint-action@v1.1.1
        with:
          input: proto

      - name: buf-generate
        run: buf generate proto

      - name: git commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: github action commit
